services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plateful
      POSTGRES_PASSWORD: plateful
      POSTGRES_DB: plateful
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U plateful -d plateful"]
      interval: 2s
      timeout: 5s
      retries: 15
