// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package storedb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CustomerName pgtype.Text        `json:"customer_name"`
	Notes        pgtype.Text        `json:"notes"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
}
