// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orders.sql

package storedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (status, customer_name, notes, total_amount)
VALUES (
  $1::text,
  $2,
  $3,
  $4
)
RETURNING id, status, created_at, updated_at, customer_name, notes, total_amount
`

type CreateOrderParams struct {
	Status       string         `json:"status"`
	CustomerName pgtype.Text    `json:"customer_name"`
	Notes        pgtype.Text    `json:"notes"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Status,
		arg.CustomerName,
		arg.Notes,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.Notes,
		&i.TotalAmount,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, status, created_at, updated_at, customer_name, notes, total_amount
FROM orders
WHERE id = $1::uuid
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.Notes,
		&i.TotalAmount,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, status, created_at, updated_at, customer_name, notes, total_amount
FROM orders
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::timestamptz IS NULL OR created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR created_at <= $3::timestamptz)
ORDER BY created_at DESC
`

type ListOrdersParams struct {
	FilterStatus pgtype.Text        `json:"filter_status"`
	CreatedFrom  pgtype.Timestamptz `json:"created_from"`
	CreatedTo    pgtype.Timestamptz `json:"created_to"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.FilterStatus, arg.CreatedFrom, arg.CreatedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.Notes,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET
  status = $1::text,
  updated_at = now()
WHERE id = $2::uuid
  AND status = $3::text
RETURNING id, status, created_at, updated_at, customer_name, notes, total_amount
`

type UpdateOrderStatusParams struct {
	NewStatus     string      `json:"new_status"`
	ID            pgtype.UUID `json:"id"`
	CurrentStatus string      `json:"current_status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.NewStatus, arg.ID, arg.CurrentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.Notes,
		&i.TotalAmount,
	)
	return i, err
}
