package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/testsabirweb/plateful/internal/graph/model"
	"github.com/testsabirweb/plateful/internal/orders"
	"github.com/testsabirweb/plateful/internal/store"
	storedb "github.com/testsabirweb/plateful/internal/store/db"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	num, err := optionalNumericString(input.TotalAmount)
	if err != nil {
		return nil, err
	}
	o, err := r.Store.CreateOrder(ctx, storedb.CreateOrderParams{
		Status:       string(orders.Pending),
		CustomerName: optionalText(input.CustomerName),
		Notes:        optionalText(input.Notes),
		TotalAmount:  num,
	})
	if err != nil {
		return nil, err
	}
	if r.Queue != nil {
		if !o.ID.Valid {
			return nil, fmt.Errorf("order missing id after insert")
		}
		if err := r.Queue.PublishOrderCreated(ctx, uuid.UUID(o.ID.Bytes)); err != nil {
			return nil, fmt.Errorf("queue publish: %w", err)
		}
	}
	return orderToGQL(o)
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	pgid, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	to, err := gqlStatusToDomain(status)
	if err != nil {
		return nil, err
	}
	cur, err := r.Store.GetOrderByID(ctx, pgid)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, fmt.Errorf("order not found")
		}
		return nil, err
	}
	from, err := orders.ParseStatus(cur.Status)
	if err != nil {
		return nil, err
	}
	if err := orders.ValidateTransition(from, to); err != nil {
		return nil, err
	}
	o, err := r.Store.UpdateOrderStatus(ctx, storedb.UpdateOrderStatusParams{
		ID:            pgid,
		CurrentStatus: string(from),
		NewStatus:     string(to),
	})
	if err != nil {
		if errors.Is(err, store.ErrStatusConflict) {
			return nil, fmt.Errorf("status conflict (order changed concurrently)")
		}
		return nil, err
	}
	return orderToGQL(o)
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	pgid, err := parseUUID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid id: %w", err)
	}
	o, err := r.Store.GetOrderByID(ctx, pgid)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return orderToGQL(o)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, filter *model.OrdersFilter) ([]*model.Order, error) {
	if r.Store == nil {
		return nil, fmt.Errorf("store not configured")
	}
	arg := storedb.ListOrdersParams{}
	if filter != nil {
		if filter.Status != nil {
			dom, err := gqlStatusToDomain(*filter.Status)
			if err != nil {
				return nil, err
			}
			arg.FilterStatus = pgtype.Text{String: string(dom), Valid: true}
		}
		if filter.CreatedFrom != nil {
			arg.CreatedFrom = pgtype.Timestamptz{Time: *filter.CreatedFrom, Valid: true}
		}
		if filter.CreatedTo != nil {
			arg.CreatedTo = pgtype.Timestamptz{Time: *filter.CreatedTo, Valid: true}
		}
	}
	rows, err := r.Store.ListOrders(ctx, arg)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Order, 0, len(rows))
	for _, row := range rows {
		o, err := orderToGQL(row)
		if err != nil {
			return nil, err
		}
		out = append(out, o)
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
